### ISSUE TITLE
Update NPM Packages typescript and @types/react to the latest version

### ISSUE THREAD

**Issue by bazmurphy** [leilafarsani/To-Do-List-Group-Work#18]
## Description

I would like to update two npm packages `typescript` and `@types/react` to their latest versions in our project.
In order to try to use Server Components without the need to tell TypeScript to ignore them.

https://nextjs.org/docs/app/building-your-application/configuring/typescript#async-server-component-typescript-error
![image](https://github.com/leilafarsani/To-Do-List-Group-Work/assets/61154071/7378afe1-017c-400e-9b70-07c60fea0c7d)

## Current Behaviour

We are using the following versions:

`typescript: v5.0.4`
`@types/react: v18.2.7`

## Desired Behaviour

The latest versions are:

`typescript: v5.1.3`
`@types/react: v18.2.9`

I hope that these updates help with the Server Component deployment issue we experienced. 
And remove the need to use comments in the code to get TypeScript to ignore the next line.

## Additional Information
.

**Comment by leilafarsani** [comment]
Great!
